baseURL = "https://security-hacks.herokuapp.com"
title = "Security Hacks"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Lotana"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "A blog on information security"
  Author = "Lotana"
  #email = "5ecur1ty.hack5.adm1n@gmail.com"
  Ganalytics = "UA-111610174-1"
  disqusShortname = "security-hacks"
  postSummariesFrontPage = 3 #Default == 4
  showReadTime = false #set to false to exclude read time from header of post

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/security_hacks"
[[params.social]]
  title = "github"
  url = "https://github.com/security-hacks"
[[params.social]]
  title = "rss"
  url = "https://www.specificfeeds.com/securitydhacks?subParam=followPub"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "About"
  url = "/about"
  weight = -180
[[menu.main]]
  name = "Archive"
  url = "/post"
  weight = -160
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = -110
